services:
  mongodb:
    image: mongo:7
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_DATABASE: secondary_indexes
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10
